version: "2.1"
services:
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    hostname: "nextcloud.${REALM}"
    volumes:
      - data_dir:/var/www/html
      - user_data:/var/www/html/data
      - custom_apps:/var/www/html/custom_apps
      - config:/var/www/html/config
    networks:
      - web
      - db
    environment: 
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${REALM}
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_UPDATE=1
      - GID=1003
      - UID=1003
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.protocol=http"
      - "traefik.docker.network=web"
      - "traefik.backend=cloud"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:cloud.${REALM}"

volumes:
  user_data:
    driver: ${VOLUME_DRIVER}
  custom_apps:
    driver: ${VOLUME_DRIVER}
  config:
    driver: ${VOLUME_DRIVER}
  data_dir:
    driver: ${VOLUME_DRIVER}

networks:
  web:
    external: true
  db:
    external: true

# $ docker exec --user www-data CONTAINER_ID php occ
# or for docker-compose:
# $ docker-compose exec --user www-data app php occ